export enum AudioChFormat {
  NONE = "none",
  MONO = "Mono",
  STEREO = "Stereo",
  K3P1P2 = "3.1.2",
  K5P1 = "5.1",
  K5P1P2 = "5.1.2",
  K5P1P4 = "5.1.4",
  K7P1 = "7.1",
  K7P1P2 = "7.1.2",
  K7P1P4 = "7.1.4",
}

export enum ChannelLabel {
  L,
  R,
  C,
  LFE,
  Ls,
  Rs,
  Lss,
  Rss,
  Lrs,
  Rrs,
  Ltf,
  Rtf,
  Ltb,
  Rtb,
}

export type ChannelLayout = {
  [layout in AudioChFormat]: ChannelLabel[];
};

export const channelLayouts: ChannelLayout = {
  [AudioChFormat.NONE]: [],
  [AudioChFormat.MONO]: [ChannelLabel.C],
  [AudioChFormat.STEREO]: [ChannelLabel.L, ChannelLabel.R],
  [AudioChFormat.K3P1P2]: [
    ChannelLabel.L,
    ChannelLabel.R,
    ChannelLabel.C,
    ChannelLabel.LFE,
    ChannelLabel.Ltf,
    ChannelLabel.Rtf,
  ],
  [AudioChFormat.K5P1]: [
    ChannelLabel.L,
    ChannelLabel.R,
    ChannelLabel.C,
    ChannelLabel.LFE,
    ChannelLabel.Ls,
    ChannelLabel.Rs,
  ],
  [AudioChFormat.K5P1P2]: [
    ChannelLabel.L,
    ChannelLabel.R,
    ChannelLabel.C,
    ChannelLabel.LFE,
    ChannelLabel.Ls,
    ChannelLabel.Rs,
    ChannelLabel.Ltf,
    ChannelLabel.Rtf,
  ],
  [AudioChFormat.K5P1P4]: [
    ChannelLabel.L,
    ChannelLabel.R,
    ChannelLabel.C,
    ChannelLabel.LFE,
    ChannelLabel.Ls,
    ChannelLabel.Rs,
    ChannelLabel.Ltf,
    ChannelLabel.Rtf,
    ChannelLabel.Ltb,
    ChannelLabel.Rtb,
  ],
  [AudioChFormat.K7P1]: [
    ChannelLabel.L,
    ChannelLabel.R,
    ChannelLabel.C,
    ChannelLabel.LFE,
    ChannelLabel.Lss,
    ChannelLabel.Rss,
    ChannelLabel.Lrs,
    ChannelLabel.Rrs,
  ],
  [AudioChFormat.K7P1P2]: [
    ChannelLabel.L,
    ChannelLabel.R,
    ChannelLabel.C,
    ChannelLabel.LFE,
    ChannelLabel.Lss,
    ChannelLabel.Rss,
    ChannelLabel.Lrs,
    ChannelLabel.Rrs,
    ChannelLabel.Ltf,
    ChannelLabel.Rtf,
  ],
  [AudioChFormat.K7P1P4]: [
    ChannelLabel.L,
    ChannelLabel.R,
    ChannelLabel.C,
    ChannelLabel.LFE,
    ChannelLabel.Lss,
    ChannelLabel.Rss,
    ChannelLabel.Lrs,
    ChannelLabel.Rrs,
    ChannelLabel.Ltf,
    ChannelLabel.Rtf,
    ChannelLabel.Ltb,
    ChannelLabel.Rtb,
  ],
};
