// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v5.29.3
// source: encoder_control_metadata.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "iamf_tools_cli_proto";

/** Controls for the encoder behavior. */
export interface EncoderControlMetadata {
  /**
   * If true [default]: Each Mix Presentation OBU will get an extra
   *                    `MixPresentationTag` with metadata describing the build
   *                    information.
   *  If false: The encoder omit adding an extra build information tag.
   */
  addBuildInformationTag?: boolean | undefined;
}

function createBaseEncoderControlMetadata(): EncoderControlMetadata {
  return { addBuildInformationTag: true };
}

export const EncoderControlMetadata: MessageFns<EncoderControlMetadata> = {
  encode(message: EncoderControlMetadata, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.addBuildInformationTag !== undefined && message.addBuildInformationTag !== true) {
      writer.uint32(8).bool(message.addBuildInformationTag);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EncoderControlMetadata {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEncoderControlMetadata();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.addBuildInformationTag = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EncoderControlMetadata {
    return {
      addBuildInformationTag: isSet(object.addBuildInformationTag)
        ? globalThis.Boolean(object.addBuildInformationTag)
        : true,
    };
  },

  toJSON(message: EncoderControlMetadata): unknown {
    const obj: any = {};
    if (message.addBuildInformationTag !== undefined && message.addBuildInformationTag !== true) {
      obj.addBuildInformationTag = message.addBuildInformationTag;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EncoderControlMetadata>, I>>(base?: I): EncoderControlMetadata {
    return EncoderControlMetadata.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EncoderControlMetadata>, I>>(object: I): EncoderControlMetadata {
    const message = createBaseEncoderControlMetadata();
    message.addBuildInformationTag = object.addBuildInformationTag ?? true;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
