// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v5.29.3
// source: temporal_delimiter.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "iamf_tools_cli_proto";

export interface TemporalDelimiterObuMetadata {
  enableTemporalDelimiters?: boolean | undefined;
}

function createBaseTemporalDelimiterObuMetadata(): TemporalDelimiterObuMetadata {
  return { enableTemporalDelimiters: false };
}

export const TemporalDelimiterObuMetadata: MessageFns<TemporalDelimiterObuMetadata> = {
  encode(message: TemporalDelimiterObuMetadata, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.enableTemporalDelimiters !== undefined && message.enableTemporalDelimiters !== false) {
      writer.uint32(8).bool(message.enableTemporalDelimiters);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TemporalDelimiterObuMetadata {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTemporalDelimiterObuMetadata();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.enableTemporalDelimiters = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TemporalDelimiterObuMetadata {
    return {
      enableTemporalDelimiters: isSet(object.enableTemporalDelimiters)
        ? globalThis.Boolean(object.enableTemporalDelimiters)
        : false,
    };
  },

  toJSON(message: TemporalDelimiterObuMetadata): unknown {
    const obj: any = {};
    if (message.enableTemporalDelimiters !== undefined && message.enableTemporalDelimiters !== false) {
      obj.enableTemporalDelimiters = message.enableTemporalDelimiters;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TemporalDelimiterObuMetadata>, I>>(base?: I): TemporalDelimiterObuMetadata {
    return TemporalDelimiterObuMetadata.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TemporalDelimiterObuMetadata>, I>>(object: I): TemporalDelimiterObuMetadata {
    const message = createBaseTemporalDelimiterObuMetadata();
    message.enableTemporalDelimiters = object.enableTemporalDelimiters ?? false;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
